name: Build and deploy mdBook

on:
  push:
    branches: ["master"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest
    environment:
      name: book
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install mdBook
        uses: taiki-e/install-action@v2
        with:
          tool: mdbook@0.5.0

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Build mdBook
        run: mdbook build docs

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: ./docs/book

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
